### 계좌 생성
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 10000
}


### 계좌 삭제
DELETE http://localhost:8080/account
Content-Type: application/json

{
"userId": 1,
"accountNumber": "1000000001"
}


### 계좌 조회
GET http://localhost:8080/account?userId=1


### 거래 생성
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 10
}


### 거래 취소
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "3ac06316af9b416496d9deb6258cd550",
  "accountNumber": "1000000000",
  "amount": 10
}


